name = "lean-sysf"
version = "0.1.0"
defaultTargets = ["lean-sysf"]

[[require]]
name = "lean-subst"
scope = "amarmaduke"
git = "https://github.com/amarmaduke/lean-subst"
rev = "705cab3ccd836e96b6051ec4d69f63f25eecac70"

[[lean_lib]]
name = "OneSortHomArityGen"

[[lean_lib]]
name = "TwoSortHet"

[[lean_lib]]
name = "LeanSysF"

[[lean_exe]]
name = "lean-sysf"
root = "Main"
